import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Posts from "./Posts";
import NavigationBar from "./NavigationBar";
import FooterBar from "./FooterBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavigationBar />
      <main className={`${styles.main} ${inter.className}`}>
        <Posts />
      </main>
      <FooterBar/>
    </>
  );
}
